# Generated by Django 2.1.2 on 2018-11-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181118_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, default='images/default_bookcover.jpg', null=True, upload_to='images/'),
        ),
    ]
